const ADD_TODO_NAME = 'ADD_TODO_NAME';
const ADD_TODO_DESCR = 'ADD_TODO_DESCR';
const ADD_NEW_TODO = 'ADD_NEW_TODO';
const CLEAR_INPUT_NAME = 'CLEAR_INPUT_NAME';
const CLEAR_INPUT_DESCR = 'CLEAR_INPUT_DESCR';

export {ADD_TODO_NAME, ADD_TODO_DESCR, ADD_NEW_TODO, CLEAR_INPUT_NAME, CLEAR_INPUT_DESCR};