const ADD_TODO_NAME = 'ADD_TODO_NAME';
const ADD_TODO_DESCR = 'ADD_TODO_DESCR';
const ADD_NEW_TODO = 'ADD_NEW_TODO';
const CLEAR_INPUT_NAME = 'CLEAR_INPUT_NAME';
const CLEAR_INPUT_DESCR = 'CLEAR_INPUT_DESCR';
const OPEN_MODAL_WINDOW = 'OPEN_MODAL_WINDOW';
const CLOSE_MODAL_WINDOW = 'CLOSE_MODAL_WINDOW';
const TODO_DONE = 'TODO_DONE';
const TODO_DELETE = 'TODO_DELETE';
const TODO_EDIT = 'TODO_EDIT';
const REMOVE_TODO = 'REMOVE_TODO';
const RESTORE_TODO = 'RESTORE_TODO';

export {ADD_TODO_NAME, ADD_TODO_DESCR, ADD_NEW_TODO, CLEAR_INPUT_NAME, CLEAR_INPUT_DESCR, OPEN_MODAL_WINDOW, CLOSE_MODAL_WINDOW, TODO_DONE, TODO_DELETE, TODO_EDIT, REMOVE_TODO, RESTORE_TODO};